# -*- mode: python ; coding: utf-8 -*-

import sys
import os
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

block_cipher = None

a = Analysis(
    ['NetworkMonitor_CTk_Full.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('I.T-Assistant.png', '.'),
        ('I.T-Assistant.ico', '.'),
    ],
    hiddenimports=[
        # Core GUI and graphics
        'customtkinter',
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',

        # Matplotlib and plotting
        'matplotlib',
        'matplotlib.backends.backend_tkagg',
        'matplotlib.pyplot',
        'matplotlib.dates',
        'matplotlib.figure',
        'matplotlib.backends._backend_tk',
        'matplotlib.backends._backend_agg',
        'matplotlib.ft2font',
        'numpy',
        'numpy.core._multiarray_umath',
        'numpy.core._multiarray_tests',
        'numpy.linalg.lapack_lite',
        'numpy.linalg._umath_linalg',

        # Network and system utilities
        'psutil',
        'psutil._psutil_windows',
        'scapy',
        'scapy.layers.l2',
        'scapy.layers.inet',
        'scapy.arch.windows',
        'manuf',
        'speedtest',
        'ping3',

        # Standard library modules
        'socket',
        'subprocess',
        'threading',
        'ipaddress',
        'platform',
        'time',
        'datetime',
        'json',
        'csv',
        'webbrowser',
        'collections',
        'concurrent.futures',
        'typing',
        'math',
        'os',
        'sys',
        're',
        'tempfile',
        'shutil',
        'glob',
        'importlib',
        'importlib.util',
        'importlib.machinery',
        'importlib.abc',
        'logging',
        'calendar',
        'base64',
        'argparse',
        'token',
        'tokenize',
        'dis',
        'ast',
        'contextlib',
        'tarfile',
        'zipfile',
        'gettext',
        'py_compile',
        'textwrap',
        'code',

        # Essential encoding modules
        'encodings',
        'encodings.aliases',
        'encodings.utf_8',
        'encodings.cp1252',
        'encodings.latin_1',
        'encodings.ascii',
        'encodings.idna',
        'codecs',
        'unicodedata',
        'stringprep',
        'urllib.parse',

        # Custom modules (optional imports)
        'settings',
        'settings_manager',
        'nmap_monitor',
        'live_monitor',
        'options_dialog',

        # Additional required modules
        'pkg_resources',
        'six',
        'certifi',
        'charset_normalizer',
        'idna',
        'requests',
        'urllib3',
        'cycler',
        'pyparsing',
        'python_dateutil',
        'kiwisolver',
        'fonttools',
        'packaging',
        'contourpy',
        'darkdetect',
        'wheel',
        'setuptools',
        'pip',
        'distutils',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Only exclude GUI frameworks we don't use
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'wx',
        'gtk',
        # Only exclude web frameworks
        'tornado',
        'django',
        'flask',
        # Only exclude development tools
        'jupyter',
        'IPython',
        'notebook',
        'sphinx',
        'pytest',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='I.T Assistant',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='I.T-Assistant.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='I.T Assistant',
)
